### ISSUE TITLE
VS 2019 Freezes when connecting to Sonar and binding projects

### ISSUE THREAD

**Issue by D9001** [SonarSource/sonarlint-visualstudio#881]
### Description

Utilizing SonarLint repeatedly freezes VS 2019 during binding operations

### Repro steps

1. Go to the SonarQube window in Team Explorer
2. Find the list of projects 
3. Select the project to which you would like to bind your solution
4. This freezes VS 2019, and it has to be force-restarted. 
5. When VS opens again, most or all projects seem to have bindings associated with it. 
6. Right click on the connected project and click "update". This will freeze VS 2019 again.

### Related information

* SonarLint for VS Version (latest)
* Visual Studio Version (VS 2019 Enterprise, latest)
* SonarQube server version (not sure)
* Languages in your solution (C# and JavaScript)

**Comment by duncanp-sonar** [comment]
Thanks for reporting this. We saw something similar with the Preview versions of VS2019 but I thought we'd fixed that by addressing #835. We'll have another look.

**Comment by D9001** [comment]
Thank you for your quick response.

I'm not sure if there is a separate issue or if it's another symptom of the same root cause, but I'm also noticing that the rules for cognitive complexity maximums are not displayed in the error list as they were in VS 2017 while using SonarLint connected to the same ruleset. Previously, the method name would be underlined when the cognitive complexity value (e.g., 20) exceeded the maximum specified in the rules (e.g., 15), and a warning message was added to the error list. It helped save me a lot of refactoring time.

**Comment by duncanp-sonar** [comment]
The cognitive complexity issue is probably unrelated, but we'll have a look at that too.

**Comment by marvinvdongen** [comment]
I can confirm this issue, experiencing the same with our entire team.

**Comment by duncanp-sonar** [comment]
The code is hanging near the end of the binding step at [this line](https://github.com/SonarSource/sonarlint-visualstudio/blob/77e604b1fb73cd834494134885c44bd0f9872a2a/src/Integration/LocalServices/ProjectSystemHelper.cs#L146)

**Comment by duncanp-sonar** [comment]
@D9001, @marvinvdongen, @cipryd,

I've published a [pre-release version](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v4.10.0.9868-alpha.1) for VS2019 that contains a fix for this bug. However, it's a threading bug so it 's difficult to know if it's a complete fix.

If possible, could someone install the pre-release version and see if it fixes the issue for your solutions? Thanks.

**Comment by duncanp-sonar** [comment]
Update: I've released [v4.10](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/v4.10.0.9879) to address this issue.
Feel free to re-open the ticket if the issue still occurs (and if it does recur, please include information about whether it is happening with old-style MSBuild projects as well as new-style SDK projects).

**Comment by ekblom** [comment]
This still occurs for me with v4.10, same setup as OP except no JS but WPF. No new-style projects.

**Comment by duncanp-sonar** [comment]
Thanks @ekblom. What does OP mean ("_same setup as OP_")?

More info: thanks, that would be very useful.
Could you collect a stack trace for the main thread please? i.e. when VS hangs, start another instance of VS, _Debug_, _Attach to process_, select the frozen _devenv.exe_, _Debug_, _Break All_. Then copy and paste the call from the _Call Stack_ tool window.

Also, how many projects do you have in your solution?

**Comment by ekblom** [comment]
I'm sorry but i can't get a call stack, "Your app has entered a break state, but no code is currently executing that is supported by the selected debug engine (e.g. only native runtime code is executing)."

We have 54 projects in our solution.

**Comment by duncanp-sonar** [comment]
Thanks for trying @ekblom. Could you add a screenshot of the top part of the SonarQube tab in the Team Explorer at the point the hang happens instead? i.e. just this bit:
![image](https://user-images.githubusercontent.com/10757559/60355787-2af8c980-99c7-11e9-860e-48a9855b3554.png).

FYI I've tried to reproduce the hang locally using a solution with a large number of projects, but haven't managed to yet.

To the other folk watching this issue: it would be useful if you could let us know whether v4.10 made any difference to your projects (it would help narrow down whether the latest hang has the same root cause as the original one or not).

**Comment by duncanp-sonar** [comment]
@ekblom I've created a debug release of SonarLint 2019 which is available [here](https://github.com/SonarSource/sonarlint-visualstudio/releases/tag/bugFix881_log_1).

It has one change that may/may not fix the binding issue.
It also has additional logging that will help diagnose where the hang is happening, if the change does not fix the issue.

Could you try out the modified version to see if it fixes the issue please? (anyone else watching this thread is welcome to try it out too). Thanks.

**Comment by ekblom** [comment]
@duncanp-sonar i have attached the log and a screenshot of the top part. And the fix did not seem work.

[sonarlint.log](https://github.com/SonarSource/sonarlint-visualstudio/files/3356288/sonarlint.log)
![image](https://user-images.githubusercontent.com/4902271/60615029-7bf52d00-9dce-11e9-92b1-751b2b14242a.png)

**Comment by duncanp-sonar** [comment]
Thanks a lot @ekblom. There's enough data in the log to show that the binding is failing at a different point. Can you tell me what type of project `HusqvarnaServiceHub.Windows.csproj` is please?

**Comment by ekblom** [comment]
@duncanp-sonar it's a regular WPF windows application targeting .NET 4.7.1.

**Comment by duncanp-sonar** [comment]
@ekblom I've tried a range of different project types/sizes/configurations/source control systems but haven't been able to repro the hang locally.

Could you provide some more info please?
* try binding again to produce another sonarlint.log as before (to check if it's failing consistently at the on the same project)
* if so, could you share that .csproj file (not the project code, just the MSBuild project file)?
* a minidump of VS at the point it hangs (select _devenv.exe_ in the _Details_ tab of the the _Task Manager_, right-click and select _Create a dump_)

Rather than share the data publicly, if you send me an email at _duncan dot pocklington at sonarsource dot com_ I can send you a link to a secured drop location. Thank you.

**Comment by ekblom** [comment]
Update after the vacation: 

I had to reinstall VS since i had enterprise installed as an evaluation, now use professional. The latest version works with this setup. 

Sorry that I can be of no more help if this is still a problem in Enterprise edition.

**Comment by duncanp-sonar** [comment]
Thanks for the update @ekblom.

SonarLint doesn't have any behaviours that are specific to an edition of VS (although it's possible that the bug is caused by some interaction between SLVS and a platform feature that is only available in VS Enterprise).

I'll close this issue. If anyone is still having issues, please create a new issue so we can start a fresh investigation. Thanks.
